# Generated by Django 5.2.12 on 2026-04-16 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Entrada (compra/reposição)'), ('out', 'Saída (venda)'), ('adjustment', 'Ajuste manual'), ('loss', 'Perda / descarte'), ('return', 'Devolução')], max_length=20, verbose_name='Tipo')),
                ('quantity', models.PositiveIntegerField(help_text='Sempre positivo. O tipo determina se entra ou sai do estoque.', verbose_name='Quantidade')),
                ('reason', models.CharField(blank=True, max_length=250, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.product', verbose_name='Produto')),
                ('user', models.ForeignKey(blank=True, help_text='Usuário que registrou a movimentação.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Movimentação de estoque',
                'verbose_name_plural': 'Movimentações de estoque',
                'ordering': ['-created_at'],
            },
        ),
    ]
