# Generated by Django 5.2.12 on 2026-04-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Entrada (compra / reposição)'), ('out', 'Saída (venda)'), ('adjustment', 'Ajuste manual'), ('loss', 'Perda / descarte'), ('return', 'Devolução de cliente')], max_length=20, verbose_name='Tipo'),
        ),
    ]
