# Generated by Django 5.2.12 on 2026-04-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='sem nome', help_text='Username', max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='telefone',
            field=models.CharField(default='sem nome', max_length=20),
            preserve_default=False,
        ),
    ]
