# Generated by Django 5.2.12 on 2026-04-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sabor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sabor',
            options={'verbose_name': 'Sabor', 'verbose_name_plural': 'Sabores'},
        ),
        migrations.AlterField(
            model_name='sabor',
            name='descricao',
            field=models.TextField(),
        ),
    ]
