# Generated by Django 5.2.12 on 2026-04-13 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(upload_to='produtos/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='sabor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sabor'),
        ),
    ]
