# Generated by Django 5.2.12 on 2026-04-24 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_options_user_created_at_user_telefone_and_more'),
        ('core', '0016_alter_pagamento_status_pagamento'),
    ]

    operations = [
    ]
