# Generated by Django 6.0.4 on 2026-06-18 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_user_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='pagamento',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='sabor',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Pagamento',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Sabor',
        ),
    ]
