# Generated by Django 5.2.6 on 2026-08-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telefone',
            field=models.CharField(blank=True, default='', help_text='Telefone para contato (opcional). Ex: (47) 99999-0000.', max_length=20, verbose_name='telefone'),
        ),
    ]
