# Generated by Django 5.2.12 on 2026-04-16 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, help_text='Gerado automaticamente. Usado em URLs e no filtro ?category=slug da API.', max_length=160, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Imagem')),
                ('is_active', models.BooleanField(default=True, help_text='Categorias inativas ficam ocultas na vitrine sem serem excluídas.', verbose_name='Ativo')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Menor número = aparece primeiro. Controla a sequência das pills na Home.', verbose_name='Ordem de exibição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, help_text='Gerado automaticamente. Usado em URLs como /produto/cookie-classico/', max_length=170, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('flavor', models.CharField(blank=True, help_text='Ex: Chocolate, Red Velvet, Nutella. Opcional.', max_length=100, verbose_name='Sabor / variação')),
                ('price', models.DecimalField(decimal_places=2, help_text='Valor exibido ao cliente (R$).', max_digits=8, verbose_name='Preço de venda')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, help_text='Custo de produção por unidade. Visível apenas no admin. Usado para calcular margem bruta e lucro.', max_digits=8, null=True, verbose_name='Preço de custo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagem')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Unidades disponíveis. Decrementado automaticamente a cada pedido.', verbose_name='Estoque')),
                ('is_active', models.BooleanField(default=True, help_text='Desativar oculta o produto da vitrine sem excluí-lo.', verbose_name='Ativo')),
                ('is_featured', models.BooleanField(default=False, help_text='Produtos em destaque aparecem primeiro na Home.', verbose_name='Em destaque')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-is_featured', 'name'],
            },
        ),
    ]
