# Generated by Django 5.2.12 on 2026-04-17 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_flavor_alter_product_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavor',
            name='slug',
            field=models.SlugField(blank=True, help_text='Gerado automaticamente. Usado em filtros de API.', max_length=120, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='flavor',
            field=models.ForeignKey(blank=True, help_text='Sabor principal do produto. Deixe em branco se não se aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.flavor', verbose_name='Sabor'),
        ),
    ]
