# Generated by Django 5.2.12 on 2026-04-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmado em'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Entregue em'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Frete ou taxa de entrega. 0 para retirada no local.', max_digits=8, verbose_name='Taxa de entrega'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_state',
            field=models.CharField(blank=True, max_length=2, verbose_name='Estado (UF)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Salvo no momento da compra. Não sofre alterações retroativas.', max_digits=8, verbose_name='Preço unitário'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='ID retornado pelo gateway (ex: Pix txid, Stripe charge_id).', max_length=200, verbose_name='ID da transação'),
        ),
    ]
